name: egrxdart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  http: ^0.13.4
  intl: ^0.15.8
  retrofit: '>=3.0.0 <4.0.0'
  logger: any #for logging purpose
  dio: ^4.0.4
  built_value: ^8.1.4
  json_annotation: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.1.7
  json_serializable: '>4.4.0'
  built_value_generator: ^8.1.4
  pedantic: ^1.9.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
